FROM python

# creates the working directory
WORKDIR /app

# copies everything to the working directory
COPY . /app

# runs the command 'python rng.py'  ## commnds must be entered as an array
CMD [ "python", "rng.py" ]